# Generated by Django 3.1 on 2020-10-05 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='uploads/')),
                ('firstname', models.CharField(default='Firstname', max_length=20)),
                ('lastname', models.CharField(default='Last Name', max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True, verbose_name='Previous School (if any)')),
                ('has_siblings', models.BooleanField(default=False)),
                ('number_of_siblings', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='o', max_length=2)),
                ('guardian', models.CharField(default='Guardian Name', max_length=255, verbose_name='Name of Guardian')),
                ('g_occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Occupation')),
                ('g_residential_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Residential Address')),
                ('g_home_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Home Phone')),
                ('g_office_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Office Phone')),
                ('g_postal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Postal Address')),
                ('lives_with_both_parents', models.BooleanField(default=False, verbose_name='Child lives with both parents')),
                ('lives_with_mother', models.BooleanField(default=False, verbose_name='Child lives with Mother')),
                ('lives_with_father', models.BooleanField(default=False, verbose_name='Child lives with Father')),
                ('assigned_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clss.clss')),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_at_birth', models.IntegerField()),
                ('present_weight', models.IntegerField()),
                ('doctor', models.CharField(default='eg. Jojo Thompson, 0540609437', max_length=255, verbose_name='Doctor name and Number')),
                ('has_asthma', models.BooleanField(default=False, verbose_name='Has Asthma?')),
                ('has_chicken_pox', models.BooleanField(default=False, verbose_name='Has Chicken Pox?')),
                ('has_convulsion', models.BooleanField(default=False, verbose_name='Has Convulsion?')),
                ('has_whooping_cough', models.BooleanField(default=False, verbose_name='Has Whooping cough?')),
                ('has_mumps', models.BooleanField(default=False, verbose_name='Has Mumps?')),
                ('has_typhoid', models.BooleanField(default=False, verbose_name='Has Typhoid?')),
                ('has_tb', models.BooleanField(default=False, verbose_name='Has Tuberculosis?')),
                ('has_measles', models.BooleanField(default=False, verbose_name='Has Measles?')),
                ('has_sickle_cell', models.BooleanField(default=False, verbose_name='Has Sickle Cell?')),
                ('allergies', models.TextField()),
                ('date_of_application', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
