# Generated by Django 3.1 on 2020-10-05 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201004_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='date_of_application',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
